s="Tops Technologies"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.center(40,"*"))
print(s.count("o"))
print(s.endswith("es"))
print(s.startswith("to"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops".isalpha())
print("123".isnumeric())
print(s.istitle())
print(s.isupper())
print(s.islower())
print("Hello".replace("l","w"))
